"""add column task_is_completed_at Task

Revision ID: 0c8a34af5b22
Revises: 6009d953a6d9
Create Date: 2026-01-30 16:35:31.177275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c8a34af5b22'
down_revision: Union[str, Sequence[str], None] = '6009d953a6d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('task_is_completed_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'task_is_completed_at')
    # ### end Alembic commands ###
