"""add column category_color to Category and delete from Task

Revision ID: 0efe5aada2ab
Revises: 4695d7bce457
Create Date: 2026-01-26 22:21:32.996752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0efe5aada2ab'
down_revision: Union[str, Sequence[str], None] = '4695d7bce457'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('category_color', sa.String(), server_default='#ef4444', nullable=False))
    op.drop_column('tasks', 'task_color')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('task_color', sa.VARCHAR(), server_default=sa.text("'#ef4444'::character varying"), autoincrement=False, nullable=False))
    op.drop_column('categories', 'category_color')
    # ### end Alembic commands ###
