"""create table Chr

Revision ID: 17ee52816c46
Revises: 245338bd0dd3
Create Date: 2026-01-31 22:13:46.700198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17ee52816c46'
down_revision: Union[str, Sequence[str], None] = '245338bd0dd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_email_is_confirm', sa.Boolean(), server_default='false', nullable=False))
    op.drop_column('users', 'user_email_is_comfirm')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_email_is_comfirm', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('users', 'user_email_is_confirm')
    # ### end Alembic commands ###
