"""add user_reg_token to User

Revision ID: 20f9720c04a2
Revises: 127b7879869a
Create Date: 2026-02-03 17:02:56.817387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20f9720c04a2'
down_revision: Union[str, Sequence[str], None] = '127b7879869a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_reg_token', sa.String(), nullable=False, server_default='not unauthorized'))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_reg_token')
    # ### end Alembic commands ###
