"""change password_is_safe to bool to User

Revision ID: 37d8e89cf819
Revises: aae060d4da6a
Create Date: 2026-01-31 18:13:08.285353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37d8e89cf819'
down_revision: Union[str, Sequence[str], None] = 'aae060d4da6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_password_is_safe',
               existing_type=sa.VARCHAR(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text("'false'::character varying"),
               postgresql_using='user_password_is_safe::boolean')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_password_is_safe',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("'false'::character varying"))
    # ### end Alembic commands ###
