"""add user_created_at to User

Revision ID: 38352685a03f
Revises: bcd92a4538f7
Create Date: 2026-02-04 22:24:28.625880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38352685a03f'
down_revision: Union[str, Sequence[str], None] = 'bcd92a4538f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_created_at')
    # ### end Alembic commands ###
