"""change bool to str task_is_completed Task

Revision ID: 451b7dd1ee5b
Revises: 7b580715d9b3
Create Date: 2026-01-27 16:02:13.676895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '451b7dd1ee5b'
down_revision: Union[str, Sequence[str], None] = '7b580715d9b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'task_is_completed',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'task_is_completed',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
