"""add column task_color for Task

Revision ID: 4695d7bce457
Revises: d9f4c9e04b9e
Create Date: 2026-01-26 22:19:48.460607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4695d7bce457'
down_revision: Union[str, Sequence[str], None] = 'd9f4c9e04b9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('task_color', sa.String(), server_default='#ef4444', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'task_color')
    # ### end Alembic commands ###
