"""add cascade delete to tasks Category

Revision ID: 52138b0fe8b1
Revises: 9808aecb3b7c
Create Date: 2026-01-28 21:20:27.224828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52138b0fe8b1'
down_revision: Union[str, Sequence[str], None] = '9808aecb3b7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
