"""user_is_active server_default changed to false

Revision ID: 5980c1e65a14
Revises: 3db96b9f2d4b
Create Date: 2026-02-03 08:23:26.472160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5980c1e65a14'
down_revision: Union[str, Sequence[str], None] = '3db96b9f2d4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
