"""add cascad to tasks Category

Revision ID: 6009d953a6d9
Revises: 52138b0fe8b1
Create Date: 2026-01-28 21:25:26.931782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6009d953a6d9'
down_revision: Union[str, Sequence[str], None] = '52138b0fe8b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tasks_task_category_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'categories', ['task_category_id'], ['category_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_task_category_id_fkey'), 'tasks', 'categories', ['task_category_id'], ['category_id'])
    # ### end Alembic commands ###
