"""create base

Revision ID: 7588115b6fd5
Revises: 
Create Date: 2026-01-23 20:56:08.774265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7588115b6fd5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('user_password', sa.String(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.Column('category_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('category_name', 'category_user_id', name='category_name_user_uc')
    )
    op.create_table('tasks',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(), nullable=False),
    sa.Column('task_text', sa.String(), nullable=False),
    sa.Column('task_important', sa.Integer(), nullable=False),
    sa.Column('task_data', sa.DateTime(timezone=True), nullable=False),
    sa.Column('task_is_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('task_category_id', sa.Integer(), nullable=False),
    sa.Column('task_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_category_id'], ['categories.category_id'], ),
    sa.ForeignKeyConstraint(['task_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('task_id'),
    sa.UniqueConstraint('task_name', 'task_user_id', name='task_name_user_uc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('categories')
    op.drop_table('users')
    # ### end Alembic commands ###
