"""change type task_data to date T

Revision ID: 7b580715d9b3
Revises: a987715b67a5
Create Date: 2026-01-27 13:23:01.536521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b580715d9b3'
down_revision: Union[str, Sequence[str], None] = 'a987715b67a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('task_date', sa.Date(), nullable=True))
    op.drop_column('tasks', 'task_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('task_data', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'task_date')
    # ### end Alembic commands ###
