"""add tfa_enabled to User

Revision ID: 8726f4f367ec
Revises: 37d8e89cf819
Create Date: 2026-01-31 18:28:17.327686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8726f4f367ec'
down_revision: Union[str, Sequence[str], None] = '37d8e89cf819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_tfa_enabled', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_tfa_enabled')
    # ### end Alembic commands ###
