"""add task_is_special to Task

Revision ID: 8ff247d58782
Revises: 451b7dd1ee5b
Create Date: 2026-01-27 19:51:10.559127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ff247d58782'
down_revision: Union[str, Sequence[str], None] = '451b7dd1ee5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('task_is_special', sa.String(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'task_is_special')
    # ### end Alembic commands ###
