"""add password_is_safe, email_is_confirm to User

Revision ID: aae060d4da6a
Revises: 0c8a34af5b22
Create Date: 2026-01-31 18:02:26.833320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aae060d4da6a'
down_revision: Union[str, Sequence[str], None] = '0c8a34af5b22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_password_is_safe', sa.String(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('user_email_is_comfirm', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_email_is_comfirm')
    op.drop_column('users', 'user_password_is_safe')
    # ### end Alembic commands ###
