"""add server_default to user_reg_tiken to User

Revision ID: bbb0780f9e04
Revises: 20f9720c04a2
Create Date: 2026-02-03 17:05:02.136297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbb0780f9e04'
down_revision: Union[str, Sequence[str], None] = '20f9720c04a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_reg_token',
               existing_type=sa.VARCHAR(),
               server_default='not register',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_reg_token',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'not unauthorized'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###
