"""add user_log_token to User

Revision ID: bcd92a4538f7
Revises: e92c9bc8e681
Create Date: 2026-02-04 12:17:01.881204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcd92a4538f7'
down_revision: Union[str, Sequence[str], None] = 'e92c9bc8e681'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_log_token', sa.String(), nullable=True))
    op.alter_column('users', 'user_reg_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_reg_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'user_log_token')
    # ### end Alembic commands ###
