"""delete datetime

Revision ID: cd6c475884eb
Revises: 94d0ecf0792c
Create Date: 2026-02-05 00:28:34.559275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd6c475884eb'
down_revision: Union[str, Sequence[str], None] = '94d0ecf0792c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('check_users', 'time_expire',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("now() + interval '10 minutes'"),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('check_users', 'time_expire',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    # ### end Alembic commands ###
