"""change server_default to user_reg_tiken to User

Revision ID: e92c9bc8e681
Revises: bbb0780f9e04
Create Date: 2026-02-03 17:05:47.462825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e92c9bc8e681'
down_revision: Union[str, Sequence[str], None] = 'bbb0780f9e04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_reg_token',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_reg_token',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'not register'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###
